[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "emu-stitch"
version = "1.1.1"
description = "Open-Source Multi-User Emulator Save Synchronizer & Profile Switcher for Linux Gaming PCs and Handhelds"
readme = "README.md"
license = { text = "MIT" }
authors = [
    { name = "R. F. Hansen-Smith", email = "3786370+R-F-HansenSmith@users.noreply.github.com" }
]
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Environment :: Console",
    "Topic :: Games/Entertainment",
    "License :: OSI Approved :: MIT License",
    "Operating System :: POSIX :: Linux",
]
dependencies = [
    "rich>=14.3.4",
]

[project.urls]
Homepage = "https://github.com/R-F-HansenSmith/emu-stitch"
Issues = "https://github.com/R-F-HansenSmith/emu-stitch/issues"
Changelog = "https://github.com/R-F-HansenSmith/emu-stitch/blob/main/CHANGELOG.md"

[project.scripts]
emu-stitch = "emu_stitch.cli:main"

[tool.hatch.build.targets.wheel]
packages = ["emu_stitch"]

[dependency-groups]
dev = ["pytest>=8.0"]
